from .bot import Mybot
from . import bot
from .commands import Commands
from .commands_channel import Commands_ch
from .commands_fn import Commands_fn
from .commands_test import Commands_test
from .music import Music
from .poll import Poll
from .setup import start
